### ISSUE TITLE
Board is empty

### ISSUE THREAD

**Issue by Bsd-us** [XertroV/tm-race-stats#1]
It is probably related to the fact I didn't pay, but I'm reporting it just in case it wasn't normal
(and if you have a tips to get it working without please let me know)

**Comment by XertroV** [comment]
it's not normal, are you in solo? do you have mlhook and mlfeed installed?

**Comment by Bsd-us** [comment]
I do have them installed, though what do you mean by solo ?
I don't have club access if that's what you meant, and I'm looking for something to work without

**Comment by XertroV** [comment]
@Bsd-us, no by solo I mean not on a server (local play). Though I would expect it to still show you on the board.

**Comment by XertroV** [comment]
How were you trying to use it? Can you post a screenshot?

**Comment by Bsd-us** [comment]
I'm trying to use it in solo, on a campaign map for example
I'll be able to send a screenshot in a few hours
But it's just empty, containing only my name and no world record at all

**Comment by Bsd-us** [comment]
Here it is, that was race 6 of current season campaign in solo 
![image](https://github.com/XertroV/tm-race-stats/assets/140352545/9b159b6c-6274-40d6-93bb-9e728ea2f1c1)

**Comment by XertroV** [comment]
Yep, race stats shows info for the current race, so wouldn't show you that anyway. 

However, watching ghosts/replays from leaderboards are a Club feature (paid access). Other plugins like ghosts++ will show you extended leaderboards; the ingame leaderboards can be enabled to always show in settings.
